/*
 * GroupDocs.Translation SDK
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 23.12.0
 * Contact: anton.perhunov@aspose.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupdocs.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.groupdocs.model.WorksheetData;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CloudFileRequest
 */
public class CloudFileRequestTest {
    private final CloudFileRequest model = new CloudFileRequest();

    /**
     * Model tests for CloudFileRequest
     */
    @Test
    public void testCloudFileRequest() {
        // TODO: test CloudFileRequest
    }

    /**
     * Test the property 'format'
     */
    @Test
    public void formatTest() {
        // TODO: test format
    }

    /**
     * Test the property 'outFormat'
     */
    @Test
    public void outFormatTest() {
        // TODO: test outFormat
    }

    /**
     * Test the property 'requestId'
     */
    @Test
    public void requestIdTest() {
        // TODO: test requestId
    }

    /**
     * Test the property 'ids'
     */
    @Test
    public void idsTest() {
        // TODO: test ids
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'size'
     */
    @Test
    public void sizeTest() {
        // TODO: test size
    }

    /**
     * Test the property 'masters'
     */
    @Test
    public void mastersTest() {
        // TODO: test masters
    }

    /**
     * Test the property 'formatting'
     */
    @Test
    public void formattingTest() {
        // TODO: test formatting
    }

    /**
     * Test the property 'origin'
     */
    @Test
    public void originTest() {
        // TODO: test origin
    }

    /**
     * Test the property 'elements'
     */
    @Test
    public void elementsTest() {
        // TODO: test elements
    }

    /**
     * Test the property 'ranges'
     */
    @Test
    public void rangesTest() {
        // TODO: test ranges
    }

    /**
     * Test the property 'shortCodeDict'
     */
    @Test
    public void shortCodeDictTest() {
        // TODO: test shortCodeDict
    }

    /**
     * Test the property 'frontMatterList'
     */
    @Test
    public void frontMatterListTest() {
        // TODO: test frontMatterList
    }

    /**
     * Test the property 'originalName'
     */
    @Test
    public void originalNameTest() {
        // TODO: test originalName
    }

    /**
     * Test the property 'separator'
     */
    @Test
    public void separatorTest() {
        // TODO: test separator
    }

    /**
     * Test the property 'isPaid'
     */
    @Test
    public void isPaidTest() {
        // TODO: test isPaid
    }

    /**
     * Test the property 'savingMode'
     */
    @Test
    public void savingModeTest() {
        // TODO: test savingMode
    }

    /**
     * Test the property 'details'
     */
    @Test
    public void detailsTest() {
        // TODO: test details
    }

}
