/*
 * GroupDocs.Translation SDK
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.2.0
 * Contact: anton.perhunov@aspose.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupdocs.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MediaToTextRequest
 */
public class MediaToTextRequestTest {
    private final MediaToTextRequest model = new MediaToTextRequest();

    /**
     * Model tests for MediaToTextRequest
     */
    @Test
    public void testMediaToTextRequest() {
        // TODO: test MediaToTextRequest
    }

    /**
     * Test the property 'sourceLanguage'
     */
    @Test
    public void sourceLanguageTest() {
        // TODO: test sourceLanguage
    }

    /**
     * Test the property 'targetLanguages'
     */
    @Test
    public void targetLanguagesTest() {
        // TODO: test targetLanguages
    }

    /**
     * Test the property 'originalFileName'
     */
    @Test
    public void originalFileNameTest() {
        // TODO: test originalFileName
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'origin'
     */
    @Test
    public void originTest() {
        // TODO: test origin
    }

    /**
     * Test the property 'savingMode'
     */
    @Test
    public void savingModeTest() {
        // TODO: test savingMode
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'targets'
     */
    @Test
    public void targetsTest() {
        // TODO: test targets
    }

    /**
     * Test the property 'format'
     */
    @Test
    public void formatTest() {
        // TODO: test format
    }

    /**
     * Test the property 'fragments'
     */
    @Test
    public void fragmentsTest() {
        // TODO: test fragments
    }

    /**
     * Test the property 'route'
     */
    @Test
    public void routeTest() {
        // TODO: test route
    }

}
