/*
 * GroupDocs.Translation SDK
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 23.12.0
 * Contact: anton.perhunov@aspose.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupdocs.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.groupdocs.model.WorksheetData;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SpreadsheetFileRequest
 */
public class SpreadsheetFileRequestTest {
    private final SpreadsheetFileRequest model = new SpreadsheetFileRequest();

    /**
     * Model tests for SpreadsheetFileRequest
     */
    @Test
    public void testSpreadsheetFileRequest() {
        // TODO: test SpreadsheetFileRequest
    }

    /**
     * Test the property 'sourceLanguage'
     */
    @Test
    public void sourceLanguageTest() {
        // TODO: test sourceLanguage
    }

    /**
     * Test the property 'targetLanguages'
     */
    @Test
    public void targetLanguagesTest() {
        // TODO: test targetLanguages
    }

    /**
     * Test the property '_file'
     */
    @Test
    public void _fileTest() {
        // TODO: test _file
    }

    /**
     * Test the property 'originalFileName'
     */
    @Test
    public void originalFileNameTest() {
        // TODO: test originalFileName
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'origin'
     */
    @Test
    public void originTest() {
        // TODO: test origin
    }

    /**
     * Test the property 'savingMode'
     */
    @Test
    public void savingModeTest() {
        // TODO: test savingMode
    }

    /**
     * Test the property 'format'
     */
    @Test
    public void formatTest() {
        // TODO: test format
    }

    /**
     * Test the property 'outputFormat'
     */
    @Test
    public void outputFormatTest() {
        // TODO: test outputFormat
    }

    /**
     * Test the property 'worksheets'
     */
    @Test
    public void worksheetsTest() {
        // TODO: test worksheets
    }

    /**
     * Test the property 'ranges'
     */
    @Test
    public void rangesTest() {
        // TODO: test ranges
    }

}
