/*
 * GroupDocs.Translation SDK
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.2.0
 * Contact: anton.perhunov@aspose.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupdocs.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StringStringTuple
 */
public class StringStringTupleTest {
    private final StringStringTuple model = new StringStringTuple();

    /**
     * Model tests for StringStringTuple
     */
    @Test
    public void testStringStringTuple() {
        // TODO: test StringStringTuple
    }

    /**
     * Test the property 'item1'
     */
    @Test
    public void item1Test() {
        // TODO: test item1
    }

    /**
     * Test the property 'item2'
     */
    @Test
    public void item2Test() {
        // TODO: test item2
    }

}
