/*
 * GroupDocs.Translation SDK
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 23.9.4
 * Contact: anton.perhunov@aspose.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupdocs.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.groupdocs.model.HttpStatusCode;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.groupdocs.JSON;

/**
 * CloudHugoResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-05T03:38:55.560817+03:00[Europe/Moscow]")
public class CloudHugoResponse {
  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private HttpStatusCode status;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public static final String SERIALIZED_NAME_FRONTMATTERS = "frontmatters";
  @SerializedName(SERIALIZED_NAME_FRONTMATTERS)
  private List<List<String>> frontmatters;

  public static final String SERIALIZED_NAME_SHORTCODES = "shortcodes";
  @SerializedName(SERIALIZED_NAME_SHORTCODES)
  private Map<String, List<List<String>>> shortcodes;

  public CloudHugoResponse() {
  }

  public CloudHugoResponse status(HttpStatusCode status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  public HttpStatusCode getStatus() {
    return status;
  }


  public void setStatus(HttpStatusCode status) {
    this.status = status;
  }


  public CloudHugoResponse message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * If file was parsed correctly or text of error
   * @return message
  **/
  @javax.annotation.Nullable
  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    this.message = message;
  }


  public CloudHugoResponse frontmatters(List<List<String>> frontmatters) {
    
    this.frontmatters = frontmatters;
    return this;
  }

  public CloudHugoResponse addFrontmattersItem(List<String> frontmattersItem) {
    if (this.frontmatters == null) {
      this.frontmatters = new ArrayList<>();
    }
    this.frontmatters.add(frontmattersItem);
    return this;
  }

   /**
   * Structure of front matter syntax
   * @return frontmatters
  **/
  @javax.annotation.Nullable
  public List<List<String>> getFrontmatters() {
    return frontmatters;
  }


  public void setFrontmatters(List<List<String>> frontmatters) {
    this.frontmatters = frontmatters;
  }


  public CloudHugoResponse shortcodes(Map<String, List<List<String>>> shortcodes) {
    
    this.shortcodes = shortcodes;
    return this;
  }

  public CloudHugoResponse putShortcodesItem(String key, List<List<String>> shortcodesItem) {
    if (this.shortcodes == null) {
      this.shortcodes = new HashMap<>();
    }
    this.shortcodes.put(key, shortcodesItem);
    return this;
  }

   /**
   * Structure of short code syntax
   * @return shortcodes
  **/
  @javax.annotation.Nullable
  public Map<String, List<List<String>>> getShortcodes() {
    return shortcodes;
  }


  public void setShortcodes(Map<String, List<List<String>>> shortcodes) {
    this.shortcodes = shortcodes;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CloudHugoResponse cloudHugoResponse = (CloudHugoResponse) o;
    return Objects.equals(this.status, cloudHugoResponse.status) &&
        Objects.equals(this.message, cloudHugoResponse.message) &&
        Objects.equals(this.frontmatters, cloudHugoResponse.frontmatters) &&
        Objects.equals(this.shortcodes, cloudHugoResponse.shortcodes);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, message, frontmatters, shortcodes);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CloudHugoResponse {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    frontmatters: ").append(toIndentedString(frontmatters)).append("\n");
    sb.append("    shortcodes: ").append(toIndentedString(shortcodes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("status");
    openapiFields.add("message");
    openapiFields.add("frontmatters");
    openapiFields.add("shortcodes");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to CloudHugoResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CloudHugoResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CloudHugoResponse is not found in the empty JSON string", CloudHugoResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CloudHugoResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CloudHugoResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        HttpStatusCode.validateJsonElement(jsonObj.get("status"));
      }
      if ((jsonObj.get("message") != null && !jsonObj.get("message").isJsonNull()) && !jsonObj.get("message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("message").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("frontmatters") != null && !jsonObj.get("frontmatters").isJsonNull() && !jsonObj.get("frontmatters").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `frontmatters` to be an array in the JSON string but got `%s`", jsonObj.get("frontmatters").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CloudHugoResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CloudHugoResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CloudHugoResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CloudHugoResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<CloudHugoResponse>() {
           @Override
           public void write(JsonWriter out, CloudHugoResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CloudHugoResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CloudHugoResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CloudHugoResponse
  * @throws IOException if the JSON string is invalid with respect to CloudHugoResponse
  */
  public static CloudHugoResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CloudHugoResponse.class);
  }

 /**
  * Convert an instance of CloudHugoResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

